spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: teamwonpage@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

#  servlet:
#    multipart:
#      max-file-size: 1MB
#      max-request-size: 3MB

  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/camp?serverTimezone=Asia/Seoul
    username: won
    password: ${MYSQL_PASSWORD}

    server:
#      address: 192.168.89.73
      port: 8080
      servlet:
        context-path: /
        encoding:
          charset: UTF-8
          enabled: true
          force: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug

jwt:
  expiration_time: 43200000 #1일
  refresh_expiration_time: 2592000000 #30일
  secret: ${JWT_SECRET}

file:
  dir: C:/study/myongjiCamp/src/main/resources/static/images/




