spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: teamwonpage@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/camp?serverTimezone=Asia/Seoul
    username: won
    password: ${MYSQL_PASSWORD}

    server:
      port: 8080
      servlet:
        context-path: /
        encoding:
          charset: UTF-8
          enabled: true
          force: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging:
  level:
    root: INFO
    com.example.myapp: DEBUG

jwt:
  expiration_time: 86400000 #1일
  secret: ${JWT_SECRET}




