# default
spring:
  profiles:
    active: dev # default
    group:
      local:  # local, common profile을 그룹지어 함께 어플리케이션 구동
        - common
      dev:   # prod, common profile을 그룹지어 함께 어플리케이션 구동
        - common

---
spring:
  config:
    activate:
      on-profile: common

  servlet:
    multipart:
      max-file-size: 1MB # 각 파일 최대 크기
      max-request-size: 10MB # 전체 요청 최대 크기

  mail:
    host: smtp.gmail.com
    port: 587
    username: teamwonpage@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

    server:
      port: 8080
      servlet:
        context-path: /
        encoding:
          charset: UTF-8
          enabled: true
          force: true

logging.level:
  org.hibernate.SQL: debug

jwt:
  expiration_time: 43200000 #1일
  refresh_expiration_time: 2592000000 #30일
  secret: ${JWT_SECRET}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_STATIC}
    stack:
      auto: false
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

---
spring:
  config:
    activate:
      on-profile: local

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/camp?serverTimezone=Asia/Seoul
    username: won
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_MYSQL_URL}
    username: ${DEV_MYSQL_USERNAME}
    password: ${DEV_MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true




